// <auto-generated />
namespace GameRecordApplication_v3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class billiardmatch : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(billiardmatch));
        
        string IMigrationMetadata.Id
        {
            get { return "202205311449499_billiard-match"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
