// <auto-generated />
namespace GameRecordApplication_v3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class gamemode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(gamemode));
        
        string IMigrationMetadata.Id
        {
            get { return "202205301444337_game-mode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
